name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-python:
    uses: ./.github/workflows/workflow.yml
    with:
      language: python
      version: "3.11"
      working-directory: backend
      run-lint: true
      run-tests: true
      upload-artifacts: true

  frontend-node:
    uses: ./.github/workflows/workflow.yml
    with:
      language: node
      version: "18"
      working-directory: frontend
      run-lint: true
      run-tests: false
      upload-artifacts: true
