name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: taskdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_HOST: localhost
      DJANGO_SETTINGS_MODULE: backend.settings


    strategy:
      matrix:
        python-version: [3.11]
        node-version: [18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Backend setup and tests
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run backend tests
        run: |
          cd backend
          pytest -v
        env:
          DATABASE_URL: postgres://postgres:postgresql@postgres:5432/taskdb
          DJANGO_SETTINGS_MODULE: backend.settings
          PYTHONPATH: .

      # Frontend setup and build
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Code quality checks
      - name: Run flake8 (Python linting)
        run: |
          pip install flake8
          flake8 backend || true

      - name: Run eslint (JS linting)
        run: |
          cd frontend
          npm install eslint
          npx eslint . || true
