# .github/workflows/ci.yml
name: CI with Gradual Enhancement

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  backend:
    strategy:
      matrix:
        py: [ "3.10", "3.11" ]
    uses: ./.github/workflows/enhanced-reusable.yml
    with:
      language: python
      version: ${{ matrix.py }}
      working-directory: backend
      run-tests: true
      run-lint: true
      enable-caching: true
      enable-coverage: true
      coverage-threshold: 80
      upload-artifacts: true
      artifact-path: dist/

  frontend:
    uses: ./.github/workflows/enhanced-reusable.yml
    with:
      language: node
      version: "20"
      working-directory: frontend
      run-tests: true
      run-lint: true
      enable-caching: true
      enable-coverage: true
      upload-artifacts: true
      artifact-path: build/
