# .github/workflows/ci.yml
name: CI with Gradual Enhancement

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  backend:
    strategy:
      matrix:
        py: [ "3.10", "3.11" ]
      fail-fast: false  # Continue testing other Python versions if one fails
    uses: ./.github/workflows/workflow.yml  # Match your actual filename
    with:
      language: python
      version: ${{ matrix.py }}
      working-directory: backend
      run-tests: true
      run-lint: true
      enable-caching: true
      enable-coverage: true
      coverage-threshold: 80
      enable-security-scan: true  # Enable security scanning
      upload-artifacts: true
      artifact-path: dist/

  frontend:
    uses: ./.github/workflows/workflow.yml  # Match your actual filename
    with:
      language: node
      version: "20"
      working-directory: frontend
      run-tests: true
      run-lint: true
      enable-caching: true
      enable-coverage: true
      coverage-threshold: 80  # Add threshold for frontend too
      enable-security-scan: true  # Enable security scanning
      upload-artifacts: true
      artifact-path: build/